-- ========================================= KEF-OSL  01.05.2014 ===========================================
-- Buisness Class
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-23',1,'Mastercard','Theodor Fransson',1);						
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-30',1,'Diners Club','Kjetil Amundsen',1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-27',1,'American Express','Andreas Rasmussen',1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-29',1,'VISA','Hjördís Orradóttir',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-29',1,'Mastercard','Ísak Leósson',1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-25',1,'VISA','Jóhann Kristinsson',1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-17',1,'VISA','Andri Valsson',1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-16',1,'VISA','Friðrik Hlynsson',1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-13',1,'VISA','Arnar Orrason',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-07',1,'Diners Club','Aeki Group AS',1);							
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-06',1,'VISA','Tuverud Partners AG',1);							
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-05',1,'Mastercard','Milljónafjelagið ehf',1);					
-- Economy Class
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Nathalie Johansson',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-01',1,'VISA','María Birgisdóttir',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-07',1,'Mastercard',' Knut Vik',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-21',1,'Diners Club','Bjørn Eide',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-12',1,'Mastercard',' Sindre Olsen',3);							
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-22',1,'VISA','Halldór Jóhannsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'VISA','Ingvar Brekason',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'Mastercard','Snorri Birgisson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'Mastercard','Margrét Benediktsdóttir',3);					
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-26',1,'VISA','Gunnar Magnússon',3);							
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-14',1,'VISA','Sigurður Þorsteinsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-11',1,'VISA','Magnús Ingvarsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-07',1,'VISA','Margrét Jónsdóttir',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-27',1,'Mastercard','Ósk Darradóttir',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Herdís Guðlaugsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-22',1,'Mastercard','Roar Pedersen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-01',1,'VISA','Astrid Jakobsen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-04',1,'Mastercard','Svein Karlsen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Solveig Sørensen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-06',1,'Mastercard','Kjell Martinsen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-06',1,'VISA','Anne Johannessen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-15',1,'Mastercard','Adam Larsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-15',1,'VISA','Daniel Olsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-15',1,'VISA','Vincent Nilsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-16',1,'VISA','Klara Björk',3);	
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-18',1,'VISA','Adam Johansson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'VISA','Freja Karlsson',3);	
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-11',1,'VISA','Liam Hansson',3);	
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-09',1,'Mastercard','Freja Karlsson',3);	 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-09',1,'Diners Club','Alfred Axelsson',3);	 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-04',1,'VISA','Ella Henriksson',3);	 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Eddie Lindström',3);	 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Jasmine Berg',3);  
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-06',1,'American Express','Noah Olsson',3);	 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-27',1,'VISA','Emil Jönsson',3);	 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-27',1,'Diners Club','Petter Knudsen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-21',1,'VISA','Anna Hanssen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'VISA','Terje Gundersen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-06',1,'VISA','Silje Jacobsen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-08',1,'VISA','Jan Kristiansen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-12',1,'Mastercard','Anna Fredriksen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-01',1,'Mastercard','Anne Myhre',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-01',1,'Mastercard','Kari Tveit',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-09',1,'VISA','Stine Jensen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-22',1,'VISA','Turid Andersen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-28',1,'American Express','Frank Haugen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-28',1,'VISA','Sander Eriksen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-16',1,'VISA','Svein Knudsen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-15',1,'American Express','Inger Moen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-15',1,'VISA','Anne Bakken',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-17',1,'VISA','Berit Ruud',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-23',1,'VISA','Line Lien',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-14',1,'VISA','Jorunn Ødegård',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-24',1,'VISA','Line Kristoffersen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-11',1,'VISA','Hilde Larsen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-21',1,'Mastercard','Kari Ahmed',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-22',1,'VISA','Kristian Strand',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-30',1,'VISA','Eivind Pedersen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-30',1,'American Express','Pål Johansen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-12',1,'VISA','Marit Gulbrandsen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-05',1,'VISA','Ida Moe',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Malin Gundersen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-02',1,'Mastercard','Aud Pedersen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-20',1,'VISA','Ragnhild Berge',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-20',1,'Diners Club','Arne Mathisen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-10',1,'Mastercard','Trond Johansen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-21',1,'Mastercard','Frank Jensen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-17',1,'VISA','Ingrid Haugen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-09',1,'VISA','Line Hansen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-29',1,'VISA','Karoline Iversen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-27',1,'VISA','Harald Haug',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-14',1,'VISA','Terje Johnsen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-18',1,'VISA','Kristoffer Bakke',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-10',1,'VISA','Kari Hansen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-20',1,'VISA','Cecilie Pedersen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-10',1,'Mastercard','Martin Johnsen',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-21',1,'American Express','Ingibjörg Ívarsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-22',1,'Diners Club','Eva Stefánsdóttir',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-22',1,'Mastercard','Sigríður Birgisdóttir',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-22',1,'VISA','Margrét Axelsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-04',1,'VISA','Marín Vilhjálmsdóttir',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-12',1,'VISA','Helga Þorsteinsdóttir',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-05',1,'Mastercard','Sigrún Eyþórsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-05',1,'VISA','Lilja Tryggvadóttir',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-17',1,'Mastercard','Sigríður Jónsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-09',1,'Mastercard','Sigríður Þorsteinsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-30',1,'Mastercard','Sigrún Grétarsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-21',1,'Mastercard','Þórunn Andradóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-17',1,'VISA','Kristín Birkisdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-11',1,'Mastercard','Auður Sveinsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-10',1,'Mastercard','Ragnhildur Óskarsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-29',1,'VISA','Áslaug Jónasdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-30',1,'Mastercard','Ingibjörg Guðjónsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-28',1,'VISA','Hrafnhildur Þorvaldsdóttir',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-26',1,'Mastercard','Helga Sveinsdóttir',3); 	
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-26',1,'VISA','Ingibjörg Eiríksdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-24',1,'Diners Club','Guðrún Sveinsdóttir',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-24',1,'Diners Club','Ragnheiður Ægisdóttir',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-01',1,'VISA','Kristín Gunnlaugsdóttir',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-04',1,'Mastercard','Brynja Birkisdóttir',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-24',1,'VISA','Steinn Halldórsson',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-25',1,'VISA','Freyr Guðnason',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-25',1,'VISA','Gunnar Magnússon',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-11',1,'Mastercard','Axel Jóhannesson',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Óli Bragason',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-01',1,'VISA','Jón Hlynsson',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'Mastercard','Bjarni Jóhannsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'VISA','Jan Kristiansen',3);  
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-23',1,'American Express','Anders Haugland',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-26',1,'VISA','Kristian Berg',3);  
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-27',1,'Mastercard','Per Andersen',3);  
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'Mastercard','Kristín Birgisdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-14',1,'Mastercard','Gunnar Magnússon',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-10',1,'VISA','Gísli Smárason',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-24',1,'VISA','Sveinn Guðjónsson',3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-30',1,'VISA','Ómar Ívarsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-14',1,'Diners Club','María Grétarsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-27',1,'VISA','Knattspyrnufélagið Þreyttur',3); 

-- ========================================= OSL-KEF  01.05.2014 ===========================================
-- First Class(24)
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-18',1,'VISA','Tindra Nyström',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-06',1,'VISA','Vilhelm Persson',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-26',1,'VISA','August Bengtsson',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-29',1,'VISA','Benjamin Arvidsson',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-05',1,'Mastercard','Erik Svensson',1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-09',1,'Mastercard','Elias Abrahamsson',1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-02',1,'VISA','Olivia Nordström',1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-22',1,'VISA','Edvard Lundqvist',1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-07',1,'VISA','Hjalmar Larsson',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'American Express','Sigge Johansson',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-02',1,'VISA','Jan Hansen',1);  
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-20',1,'Mastercard','Anne Nilsen',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-23',1,'Mastercard','Maria Haugland',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-15',1,'American Express','Anne Hagen',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-08',1,'VISA','Hans Olsen',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-11',1,'VISA','Karin Ellingsen',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-23',1,'Diners Club','Kristian Sandvik',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-24',1,'VISA','Ari Antonsson',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-25',1,'Mastercard','Axel Valdimarsson',1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-04',1,'Mastercard','Bjarni Hjaltason',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-02',1,'VISA','Kristín Guðmundsdóttir',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-01',1,'Mastercard','Breki Hilmarsson',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-18',1,'Mastercard','Jakob Björnsson',1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-10',1,'Mastercard','Sævar Andrason',1); 
-- Economy Class
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Olivia Karlsson',3); 	
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-08',1,'VISA','Maja Pettersson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-28',1,'VISA','Leo Lindgren',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-20',1,'Mastercard','Ella Sandström',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'VISA','Frank Nilsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-29',1,'Mastercard','Emma Persson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-11',1,'American Express','Elsa Svensson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Jonathan Andersson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-18',1,'Mastercard','Theodor Wallin',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-02',1,'VISA','Filip Bergström',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-28',1,'VISA','Alfred Axelsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-15',1,'Mastercard','Alva Sjöberg',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-26',1,'VISA','Alicia Persson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-29',1,'American Express','Elly Pettersson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-22',1,'VISA','Ellen Larsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-06',1,'VISA','Elsa Jonsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'Mastercard','Tyra Björk',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'Mastercard','Nova Hermansson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-26',1,'VISA','Elliot Lindholm',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-05',1,'Mastercard','Klara Persson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-17',1,'VISA','Julie Andreassen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-11',1,'Mastercard','Harald Olsen',3);  
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-16',1,'Mastercard','Thomas Svendsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-28',1,'American Express','Gunn Lie',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-13',1,'VISA','Kari Hanssen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-23',1,'American Express','Odd Strand',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-22',1,'VISA','Einar Andersen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-04',1,'Mastercard','Sigrid Abrahamsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-01',1,'VISA','Camilla Hansen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-20',1,'VISA','Camilla Berg',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-25',1,'Mastercard','Ole Dahl',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-28',1,'VISA','Maria Olsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-02',1,'VISA','Eirik Amundsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-27',1,'Diners Club','Randi Bøe',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Kjell Pedersen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-08',1,'VISA','Janne Rasmussen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'VISA','Malin Mikkelsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Lise Larsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-25',1,'VISA','Tone Nielsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Thomas Andersen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-16',1,'VISA','Stian Nilsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-05',1,'Mastercard','Stian Pettersen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'American Express','Olav Jensen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-12',1,'VISA','Silje Hanssen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-07',1,'American Express','Per Pedersen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-17',1,'Mastercard','Irene Larsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-16',1,'VISA','Eivind Olsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-12',1,'VISA','Einar Christensen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-07',1,'VISA','Terje Kristiansen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-05',1,'Mastercard','Anne Andreassen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Lars Andersen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-14',1,'VISA','Hilde Henriksen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-09',1,'VISA','Unni Olsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Julie Johansen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'VISA','Julie Jørgensen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'Diners Club','Alf Moe',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-25',1,'VISA','Jørgen Kristensen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-09',1,'VISA','Anne Larsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-06',1,'VISA','Eva Moen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-10',1,'VISA','Terje Olsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Astrid Kristiansen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-21',1,'VISA','Linda Hansen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-07',1,'Mastercard','Torill Andersen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-13',1,'VISA','Karin Vik',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-04',1,'VISA','Tonje Holm',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-17',1,'Diners Club','Inger Haugen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-22',1,'VISA','Solveig Olsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-12',1,'VISA','Tore Nygård',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-25',1,'Diners Club','Øyvind Nygård',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-24',1,'Mastercard','Ragnhild Jakobsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-01',1,'Diners Club','Tore Danielsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-15',1,'VISA','Tobias Nilsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'Mastercard','Elin Karlsen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-10',1,'VISA','Gerd Haugen',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-11',1,'American Express','Arne Berge',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'Mastercard','Aron Þórisson',3);  
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-21',1,'VISA','Páll Þórisson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-10',1,'American Express','Róbert Emilsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-12',1,'VISA','Ágúst Róbertsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-25',1,'Mastercard','Bragi Vilhjálmsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Þórir Brekason',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-14',1,'VISA','Auður Viðarsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-07',1,'American Express','Líf Arnardóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-12',1,'VISA','Ragnheiður Sigurðardóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-27',1,'American Express','Andri Freysson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-10',1,'Diners Club','Ágústa Þorvaldsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-04',1,'VISA','Andri Arnarson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-23',1,'VISA','Darri Tryggvason',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-20',1,'VISA','Ólafur Friðriksson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-04',1,'Mastercard','Valgerður Kjartansdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-06',1,'VISA','Gísli Arnarson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-08',1,'VISA','Hulda Brekadóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-24',1,'VISA','Trausti Þórarinsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-14',1,'Mastercard','Ásdís Sindradóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-08',1,'VISA','Hanna Kristinsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-25',1,'American Express','Guðmundur Davíðsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-21',1,'VISA','Ari Arason',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-18',1,'Mastercard','Rúnar Logason',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-16',1,'Mastercard','Bragi Kristinsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-14',1,'VISA','Þórir Heiðarsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-23',1,'Mastercard','Jóhann Baldursson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-02',1,'American Express','Eva Reynisdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-10',1,'VISA','Árni Þórisson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-29',1,'VISA','Bjarki Arnarson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-18',1,'VISA','Þór Bergmannsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-04',1,'Mastercard','Einar Hermannsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-18',1,'Mastercard','Guðrún Aðalsteinsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-21',1,'Mastercard','Guðmundur Daníelsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-09',1,'VISA','Ólafur Sverrisson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-28',1,'American Express','Guðbjörg Bergmannsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-07',1,'Mastercard','Kristín Káradóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-20',1,'VISA','Sigurður Bergmannsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-21',1,'Mastercard','Halldór Atlason',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-16',1,'VISA','Ingvar Kristófersson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'VISA','Katrín Björnsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-19',1,'Mastercard','Bára Eyþórsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-04',1,'American Express','Stefanía Ingólfsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-16',1,'VISA','Ólöf Arnórsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-06',1,'VISA','Þóra Jónsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-22',1,'VISA','Sigríður Ívarsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-06',1,'Mastercard','Friðrik Antonsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-21',1,'VISA','Bryndís Gunnarsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-23',1,'VISA','Sóley Steinsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-04',1,'Mastercard','Margrét Alexandersdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-09',1,'Diners Club','Þórunn Snæsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-15',1,'Diners Club','Ragnheiður Axelsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-21',1,'VISA','Elín Steinsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-04',1,'Diners Club','Margrét Arnardóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-09',1,'American Express','Stefán Stefánsson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-06',1,'VISA','Ragnheiður Bjarnadóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-27',1,'American Express','Magnús Árnason',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-13',1,'VISA','Hildur Gunnlaugsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-15',1,'VISA','Kári Birkisson',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-03',1,'VISA','Bjarni Darrason',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-13',1,'VISA','Katrín Þórarinsdóttir',3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,classID)values('2016-07-13',1,'VISA','Ingibjörg Guðlaugsdóttir',3);